"""add_car_models

Revision ID: be82c5b0802a
Revises: 9dd0dc2b8e79
Create Date: 2025-03-23 22:59:42.505659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be82c5b0802a'
down_revision: Union[str, None] = '9dd0dc2b8e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('models',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'USED', name='carcondition'), nullable=False),
    sa.Column('fuel_type', sa.Enum('PETROL', 'DIESEL', 'ELECTRIC', 'HYBRID', 'GAS', name='fueltype'), nullable=False),
    sa.Column('transmission', sa.Enum('MANUAL', 'AUTOMATIC', 'ROBOT', 'VARIATOR', name='transmissiontype'), nullable=False),
    sa.Column('drive_type', sa.Enum('FRONT', 'REAR', 'FULL', name='drivetype'), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('engine_volume', sa.Float(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('photos', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.drop_table('models')
    op.drop_table('brands')
    # ### end Alembic commands ###
